name: HMT Stock Checker Every 2 Minutes

on:
  schedule:
    # Every 5 mins between 2:30 AM and 2:29 PM UTC (which is 8:00 AM – 8:00 PM IST)
    - cron: "*/5 2-14 * * *"

    # Every 10 mins from 2:30 PM to 2:29 AM UTC (which is 8:00 PM – 8:00 AM IST)
    - cron: "*/10 0-1,15-23 * * *"
  workflow_dispatch:  # Manual run button

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TOKEN }}
      CHANNEL_ID: ${{ secrets.CHANNEL_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the Discord stock checker
        run: python hmt-bot.py 
